class Recebimentos(object):

    def __init__(slef):
        clienteId = 0
        filialId = 0
        filialCodigo = ''
        key = ''
        lancamentoId = 0
        statusConciliacao = ''
        adquirente = ''
        cnpj = ''
        bandeira = ''
        produto = ''
        numeroDaParcela = 0
        quantidadeDeParcelas = 0
        nsu = ''
        autorizacao = ''
        tid = ''
        valorBrutoConta = 0.00
        valorBrutoContraPartida = 0.00
        valorLiquidoConta = 0.00
        valorLiquidoContraPartida = 0.00
        taxaConta = 0.00
        taxaContraPartida = 0.00
        banco = ''
        agencia = ''
        conta = ''
        terminal = ''
        estabelecimento = ''
        dataVenda = ''
        dataRecebimento = ''
        sistemaOrigem = ''
        dataDePrevisaoDoVencimento = ''
        notaFiscal = ''

    def parse(self, recebimento):
        self.clienteId = int(recebimento['clienteId'])
        self.filialId = int(recebimento['filialId'])
        self.filialCodigo = recebimento['filialCodigo']
#     self.key = recebimento['key']
        self.lancamentoId = int(recebimento['lancamentoId'])       
        self.statusConciliacao = recebimento['statusConciliacao']
        self.adquirente = recebimento['adquirente']
#     self.cnpj = recebimento['cnpj']
        self.bandeira = recebimento['bandeira']
        self.produto = recebimento['produto']
#     self.numeroDaParcela = int(recebimento['numeroDaParcela'])       
#     self.quantidadeDeParcelas = int(recebimento['quantidadeDeParcelas'])       
        self.nsu = recebimento['nsu']
        self.autorizacao = recebimento['autorizacao']
#     self.tid = recebimento['tid']
        self.valorBrutoConta = float(recebimento['valorBrutoConta'])
        self.valorBrutoContraPartida = float(recebimento['valorBrutoContraPartida'])
        self.valorLiquidoConta = float(recebimento['valorLiquidoConta'])
        self.valorLiquidoContraPartida = float(recebimento['valorLiquidoContraPartida'])
#     self.taxaConta = float(recebimento['taxaConta'])
#     self.taxaContraPartida = float(recebimento['taxaContraPartida'])
#     self.banco = recebimento['banco']
#     self.agencia = recebimento['conta']
        self.conta = recebimento['autorizacao']
        self.terminal = recebimento['terminal']
        self.estabelecimento = recebimento['estabelecimento']
#     self.dataVenda = recebimento['dataVenda']
        self.dataRecebimento = recebimento['dataRecebimento']
        self.sistemaOrigem = recebimento['sistemaOrigem']
#     self.dataDePrevisaoDoVencimento = recebimento['dataDePrevisaoDoVencimento']
#     self.notaFiscal = recebimento['notaFiscal']